### ISSUE TITLE
Didn't get anything at Frequency Spectrum

### ISSUE THREAD

**Issue by mamun-bd** [Seank23/MusicAnalyser#5]
I didn't get anything at Frequency Spectrum. 
Would you please share the procedure to display Frequency Spectrum?

I think, I am not get Script information.

**Comment by Seank23** [comment]
Hi,
I haven't had a chance to write much documentation so apologies.

Underneath the Processing Chain there is a dropdown to select a preset, I'd recommend selecting either New-FFT-Magnitude or HarmonicProductSpectrum, this will set up the scripts used according to the preset you select. If you do not see any presets in the dropdown then let me know.

Next click the Open button and select an audio file (must be .wav or.mp3) to load in, after a few seconds you should see a waveform of the audio file appear, you should then be able to press the Play button which will start playing the audio and the frequency analysis should be displayed on the spectrum.

If you have any other problems let me know and I'll try to help :)

**Comment by mamun-bd** [comment]
Hello,
Thank you for your immediate feedback.

When i run this source code then i got following issues:
1. XanderUI is missing
2. Scripts folder error

I downloded XanderUI from internet & created Scripts folder at Debug folder then i can run this project without any error.

As per your feedback, I checked your instructions. but i didn't see any Preset information at dropdown menu.

Please help me for displaying Preset information.

Thank You for your support.

**Comment by Seank23** [comment]
Ah I see, you're trying to run the source code. You will need to add the XanderUI.dll as a reference in the project, then go to the folder where the code was built (Debug folder) and extract the scripts folder I've attached [Scripts.zip](https://github.com/Seank23/MusicAnalyser/files/5996385/Scripts.zip), this contains all the scripts and presets. It should run fine now.

If you just want to play about with the app I'd recommend downloading the release version [here](https://github.com/Seank23/MusicAnalyser/releases/tag/0.7.0), it should have everything set up for you.

Hope this helps!

**Comment by mamun-bd** [comment]
Now it's working...
Thank you for your help.

**Comment by mamun-bd** [comment]
is it possible to detect pitch when recording ongoing?
If possible then would you please share the steps?

**Comment by Seank23** [comment]
> is it possible to detect pitch when recording ongoing?
> If possible then would you please share the steps?

I couldn't get that to work unfortunately so you have to record your audio first then play it back with the analysis. I will revisit this in the future as it's a feature I'd definitely like to have in the app.
