### ISSUE TITLE
License

### ISSUE THREAD

**Issue by float3** [Seank23/MusicAnalyser#8]
Hi, I would like to use this. Have you decided on a license? If not, could you license it as MIT or a similar license?

**Comment by Seank23** [comment]
Hi,

Yes, please feel free to use this. I have not thought about licencing in detail yet but I intend for this project to be completely open source and I'll update the licence details when I get a chance.

Also, apologies for the lack of usage information, I am currently working on a full user guide for the program but I have found the time to complete it yet.

**Comment by float3** [comment]
Alright sounds good, thank you!

**Comment by Seank23** [comment]
I've licensed the project under GPLv3.
A user guide is now available.
